#!/usr/bin/env python
# coding: utf-8

# In[2]:


# Lab1:------------------------------
#  Analyze the relationship between the size of houses (measured in square
# footage) and their selling prices in a particular neighborhood. You have collected
# data on various houses in that neighborhood.Create a scatter plot using the
# below data and share your conclusion/analysis.
# Input:
# square_footage = np.array([1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800,
# 3000])
# selling_prices = np.array([250, 290, 315, 380, 410, 450, 500, 525, 570, 610])




import numpy as np
import matplotlib.pyplot as plt

square_footage = np.array([1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000])
selling_prices = np.array([250, 290, 315, 380, 410, 450, 500, 525, 570, 610])

plt.figure(figsize=(10, 6))
plt.scatter(square_footage, selling_prices, color='green', marker='o')
plt.title('Relationship Between House Size and Selling Price')
plt.xlabel('Square Footage')
plt.ylabel('Selling Price (in thousands)')
plt.grid(True)
plt.show()


# In[11]:


# question 2==========================

# Create a pie chart to visualize the distribution of your monthly income by
# source. You have collected data on the various sources of your income, such as
# salary, freelance work, investments, and rental income. Share your
# conclusion/analysis.
# Input:
# income_sources = ['Salary', 'Freelance', 'Investments', 'Rental', 'Other']
# monthly_income = [5000, 1500, 1000, 600, 400]

import matplotlib.pyplot as plt


income_sources = ['Salary', 'Freelance', 'Investments', 'Rental', 'Other']
monthly_income = [5000, 1500, 1000, 600, 400]

col = ['lightblue', 'lightcoral', 'lightgreen', 'lightpink', 'lightgrey']
plt.figure(figsize=(9, 6))

plt.pie(monthly_income, labels=income_sources, colors=col, autopct='%1.3f%%',
         radius=0.9, shadow=True, wedgeprops={"linewidth": 3})


plt.title('Distribution of Monthly Income by Source')


plt.axis('equal')  
plt.show()



# In[21]:


# Lab3:----------------------------
# Create a pie chart to illustrate the distribution of a company's revenue
# across its various business segments. You have collected data on the revenue
# generated by each segment, such as Product A, Product B, Services, and
# Licensing. Share your conclusion/analysis.
# Input:
# segments = ['Product A', 'Product B', 'Services', 'Licensing']
# revenue_percentages = [45, 25, 15, 15]


import matplotlib.pyplot as plt

# Data
segments = ['Product A', 'Product B', 'Services', 'Licensing']
revenue_percentages = [45, 25, 15, 15]

# Create the pie chart
plt.figure(figsize=(10, 6))
col = ['lightblue', 'yellow', 'red','lightpink' , 'green']
plt.pie(revenue_percentages, labels=segments, colors=col, autopct='%1.6f%%',
         radius=0.9, shadow=True, wedgeprops={"linewidth": 7})

# Add title
plt.title('Revenue Distribution Across Business Segments')

# Display the plot
plt.axis('equal')  # Equal aspect ratio ensures the pie chart is circular.
plt.show()


# In[30]:


# categories: Electronics, Clothing, Home & Garden, and Sports & Outdoors. Share
# your conclusion/analysis.
# Input:
# months = np.arange(1, 13)
# electronics_sales = np.array([25000, 28000, 31000, 27000, 30000, 32000, 35000,
# 36000, 38000, 39000, 41000, 42000])
# clothing_sales = np.array([15000, 16000, 17000, 18000, 19000, 20000, 21000, 22000,
# 23000, 24000, 25000, 26000])
# home_garden_sales = np.array([18000, 19000, 20000, 21000, 22000, 23000, 24000,
# 25000, 26000, 27000, 28000, 29000])
# sports_outdoors_sales = np.array([12000, 13000, 14000, 15000, 16000, 17000, 18000,
# 19000, 20000, 21000, 22000, 23000])



import numpy as np
import matplotlib.pyplot as plt
months = np.arange(1, 13)
# 1 graph========================(electronics_sales)
electronics_sales = np.array([25000, 28000, 31000, 27000, 30000, 32000, 35000, 36000, 38000, 39000, 41000, 42000])
plt.figure(figsize=(2, 3))
plt.plot(months, electronics_sales, marker='o', linestyle='-', color='b', label='Electronics')
# 2graph================(clothing_sales)
clothing_sales = np.array([15000, 16000, 17000, 18000, 19000, 20000, 21000, 22000, 23000, 24000, 25000, 26000])
plt.figure(figsize=(2, 3))
plt.plot(months, clothing_sales, marker='o', linestyle='-', color='g', label='Clothing')

# 3graph================(home_garden_sales)
home_garden_sales = np.array([18000, 19000, 20000, 21000, 22000, 23000, 24000, 25000, 26000, 27000, 28000, 29000])
plt.figure(figsize=(2, 3))
plt.plot(months, home_garden_sales, marker='o', linestyle='-', color='r', label='Home & Garden')

# 4graph================(sports_outdoors_sales )

sports_outdoors_sales = np.array([12000, 13000, 14000, 15000, 16000, 17000, 18000, 19000, 20000, 21000, 22000, 23000])
plt.figure(figsize=(2, 3))
plt.plot(months, sports_outdoors_sales, marker='o', linestyle='-', color='c', label='Sports & Outdoors')

plt.title('Monthly Sales Data by Category')
plt.xlabel('Month')
plt.ylabel('Sales (in dollars)')
plt.legend()


plt.grid(True)
plt.xticks(months)
plt.show()

